import Foundation

/// Alphabet metadata index (DasherCore `Data/alphabets/alphabet_index.json`,
/// generated by `Scripts/generate-alphabet-index.py`). One entry per unique
/// alphabet: lang code, ISO-15924 script, direction, corpus tier, symbol count.
///
/// Port of Dasher-Android's `AlphabetIndex.kt` (parity PR). Uses:
///  - Locale-follow: pick a sensible default alphabet for the device locale
///    (only while the user hasn't explicitly chosen one).
///  - Picker badges: script / direction next to each alphabet name.
///
/// Falls back to an empty index when the file is missing or unreadable — the
/// engine's own name scan (CAlphIO::ScanNameIndex) is independent, so the app
/// keeps working; only the metadata niceties degrade.
public struct AlphabetInfo: Equatable, Sendable {
    public let id: String
    public let orientation: String
    public let lang: String?
    public let script: String?
    public let scriptName: String?
    public let chars: Int
    public let source: String

    public var rtl: Bool { orientation == "rtl" }
}

public enum AlphabetIndex {
    /// The engine's historical default — preferred within its tier for
    /// locale-follow.
    public static let engineDefaultAlphabet = "English with limited punctuation"

    private static var cached: [AlphabetInfo]?

    /// Load the index from the app bundle's Data folder (cached). Thread-safe
    /// enough for our use (called from the main actor).
    public static func load(dataDir: String) -> [AlphabetInfo] {
        if let cached { return cached }
        let url = URL(fileURLWithPath: dataDir)
            .appendingPathComponent("alphabets", isDirectory: true)
            .appendingPathComponent("alphabet_index.json")
        struct IndexFile: Decodable {
            struct Entry: Decodable {
                let id: String
                let orientation: String?
                let lang: String?
                let script: String?
                let scriptName: String?
                let chars: Int?
                let source: String?
            }
            let alphabets: [Entry]
        }
        guard let data = try? Data(contentsOf: url),
              let file = try? JSONDecoder().decode(IndexFile.self, from: data) else {
            cached = []
            return []
        }
        let list = file.alphabets.map {
            AlphabetInfo(id: $0.id,
                         orientation: $0.orientation ?? "ltr",
                         lang: ($0.lang?.isEmpty == false) ? $0.lang : nil,
                         script: ($0.script?.isEmpty == false) ? $0.script : nil,
                         scriptName: ($0.scriptName?.isEmpty == false) ? $0.scriptName : nil,
                         chars: $0.chars ?? 0,
                         source: $0.source ?? "legacy")
        }
        cached = list
        return list
    }

    /// Best alphabet for a BCP-47 locale tag ("ar", "pt-BR", "zh-Hans-CN").
    /// Match order: exact lang code, then language+script, then language
    /// prefix. Ranking within the matched set: maintained > worldalphabets >
    /// legacy, the engine default first within its tier, then fuller
    /// alphabets. Defaults must land on maintained alphabets — see the
    /// Android note about WorldAlphabets trees barely expanding.
    public static func suggest(list: [AlphabetInfo], localeTag: String) -> AlphabetInfo? {
        if list.isEmpty { return nil }
        let tag = localeTag.replacingOccurrences(of: "_", with: "-")
        let parts = tag.split(separator: "-")
        let language = parts.first.map { $0.lowercased() } ?? ""
        if language.isEmpty { return nil }
        let script: String? = parts.dropFirst().first.flatMap { sub -> String? in
            guard sub.count == 4 else { return nil }
            return sub.prefix(1).uppercased() + sub.dropFirst().lowercased()
        }

        func tier(_ a: AlphabetInfo) -> Int {
            switch a.source {
            case "maintained": return 0
            case "worldalphabets": return 1
            default: return 2
            }
        }
        // Score: better (lower) tier dominates; within a tier the engine
        // default wins, then the fuller alphabet (mirrors Android's fixed
        // scoring — tier multiplied INTO the rank, not added).
        func score(_ a: AlphabetInfo) -> Int {
            let tierRank = 2 - tier(a)
            let defaultBonus = a.id == engineDefaultAlphabet ? 1 : 0
            return tierRank * 1_000_000 + defaultBonus * 500_000 + min(a.chars, 499_999)
        }

        let candidates = list.filter { $0.lang != nil }
        // 1. exact lang code (covers "zh-Hans" style entries directly)
        if let hit = candidates.filter({ $0.lang!.caseInsensitiveCompare(tag) == .orderedSame })
            .max(by: { score($0) < score($1) }) {
            return hit
        }
        // 2. language + script ("zh-Hans-CN" → lang "zh-Hans")
        if let script,
           let hit = candidates.filter({ $0.lang == "\(language)-\(script)" })
            .max(by: { score($0) < score($1) }) {
            return hit
        }
        // 3. language prefix
        return candidates
            .filter { $0.lang!.hasPrefix(language) }
            .max(by: { score($0) < score($1) })
    }

    public static func suggestForLocale(dataDir: String, localeTag: String) -> AlphabetInfo? {
        suggest(list: load(dataDir: dataDir), localeTag: localeTag)
    }
}

/// Locale-follow state (RFC 0003 language-selection principle; shared across
/// the app and keyboard via the app group so a pick in either pins it).
public enum AlphabetFollow {
    static let key = "alphabet_follows_locale"

    public static var followsLocale: Bool {
        get {
            SharedDefaults.fallback.object(forKey: key) as? Bool ?? true
        }
        set {
            if newValue {
                SharedDefaults.fallback.removeObject(forKey: key)
            } else {
                SharedDefaults.fallback.set(false, forKey: key)
            }
        }
    }
}
